<SqlMigrate>
	<Id>104</Id>
	<AppId>5</AppId>
	<MigrateName>20200322125455_CREATE_placement.sql</MigrateName>
	<MigrateSql>DROP TABLE IF EXISTS `placement`;&#xA;DROP TABLE IF EXISTS `element`;&#xA;CREATE TABLE `placement` (&#xA;  `id` bigint(20) NOT NULL AUTO_INCREMENT,&#xA;  `app_id` bigint(20) NOT NULL DEFAULT &#39;0&#39;,&#xA;  `placement_name` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `placement_label` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `placement_type` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `placement_desc` longtext COLLATE utf8_bin NOT NULL,&#xA;  `created_by` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `created_time` datetime NOT NULL,&#xA;  `last_updated_by` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `last_updated_time` datetime NOT NULL,&#xA;  `element_limit` bigint(20) NOT NULL DEFAULT &#39;0&#39;,&#xA;  PRIMARY KEY (`id`)&#xA;) ENGINE=InnoDB AUTO_INCREMENT=89 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;&#xA;CREATE TABLE `element` (&#xA;  `id` bigint(20) NOT NULL AUTO_INCREMENT,&#xA;  `placement` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `element_name` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `element_label` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `content` longtext COLLATE utf8_bin NOT NULL,&#xA;  `linked_refer` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `img_path` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `status` bigint(20) NOT NULL DEFAULT &#39;0&#39;,&#xA;  `navigation_level` bigint(20) NOT NULL DEFAULT &#39;0&#39;,&#xA;  `navigation_parent_id` bigint(20) NOT NULL DEFAULT &#39;0&#39;,&#xA;  `md_content` longtext COLLATE utf8_bin NOT NULL,&#xA;  `created_by` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `created_time` datetime NOT NULL,&#xA;  `last_updated_by` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT &#39;&#39;,&#xA;  `last_updated_time` datetime NOT NULL,&#xA;  PRIMARY KEY (`id`)&#xA;) ENGINE=InnoDB AUTO_INCREMENT=366 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;</MigrateSql>
	<MigrateHash>4mqR+5HUpGHmUNtBJtzrmQvbQH+/UE2GbiYSA28MVWs=</MigrateHash>
	<Effective>true</Effective>
	<CreatedBy>SYSTEM</CreatedBy>
	<CreatedTime>2020-03-22T12:54:55+08:00</CreatedTime>
	<LastUpdatedBy>SYSTEM</LastUpdatedBy>
	<LastUpdatedTime>2020-03-22T12:59:20+08:00</LastUpdatedTime>
</SqlMigrate>