name: linkknown
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  # Flutter 的网络请求库
  dio: ^3.0.9
  # Flutter 状态管理 Provider
  provider: ^3.2.0
  # Flutter 路由依赖库
  fluro: ^1.5.1
  flutter_screenutil: ^2.1.0
  fluttertoast: ^3.1.3
  flutter_swiper: ^1.1.6
  shared_preferences: ^0.4.3
  flutter_svg: ^0.17.4
  event_bus:  ^1.1.1
  flutter_easyrefresh: ^2.1.1
  cached_network_image: ^2.2.0
#  flutter_spinkit: ^4.1.2
  fijkplayer: ^0.8.7
  path_provider: ^1.6.11
  sprintf: ^4.0.2
  share: ^0.6.4+3
  image_picker: 0.6.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/linkknown.jpg
    - images/home53.png
    - images/banner_biancheng.png
    - images/banner_coupon.png
    - images/banner_huodong.png
    - images/banner_shaoer.png
    - images/image_wenjuan.png
    - images/image_kaoshi.png
    - images/add.svg
    - images/setting.svg
    - images/lingdang.svg
    - images/not_found.png
    - images/ic_views.png
    - images/ic_list_counts.png
    - images/ic_video.png
    - images/ic_order.png
    - images/ic_shopping_cart.png
    - images/ic_login.png
    - images/ic_regist.png
    - images/ic_logout.png
    - images/ic_share.png
    - images/icon_list.svg
    - images/icon_grid.svg
    - images/ic_coupon.svg
    - images/ic_shopping_cart.svg
    - images/ic_order.svg
    - images/ic_activity.svg
    - images/ic_kaoshi.svg
    - images/ic_cloud_blog.png
    - images/ic_personal_center.png
    - images/ic_course.png
    - images/ic_about.png
    - images/ic_advise.png
    - images/ic_link.png
    - images/ic_operate_bg.png
    - images/ic_play.svg
    - images/ic_play2.svg
    - images/ic_share.svg
    - images/ic_praise.svg
    - images/ic_collect.svg
    - images/nuli.jpg
    - images/coupon_red.png
    - images/coupon_grey.png
    - images/business.jpg
    - images/ic_pay_result_success.png
    - images/ic_pay_result_fail.png
    - images/ic_pay_result_wait_for_pay.png
    - images/ic_pay_result_cancel.png
    - images/ic_male.png
    - images/ic_female.png
    - images/personal_center_img01.jpg
    - images/personal_center_img02.jpg
    - images/personal_center_img03.jpg
    - images/personal_center_img04.jpg
    - images/ic_fab_play.png
    - images/ic_add_blog.svg
    - images/page_coming_soon.gif
    - images/ic_hot_logo.png
    - images/loading_01.png
    - images/loading_02.png
    - images/loading_03.png
    - images/loading_04.png
    - images/loading_05.png
    - images/loading_06.png
    - images/loading_07.png
    - images/fenlei.png
    - images/kaoshi.png
    - images/video.png
    - images/zhaopin.png
    - images/book.png
    - images/huodong.png
    - images/coupon.png
    - images/personalCenter.png
    - images/unlogin_head_no_circle.png
    - images/unlogin_head_with_circle.png
    - images/my_center_01.jpg
    - images/shoppingCart_green.png
    - images/no_data.png
    - images/video_play.png
    - images/ic_clock.svg
    - images/order_asc.svg
    - images/order_desc.svg
    - images/icon_add.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
